### ISSUE TITLE
Error al conectarse 2 veces con un cliente

### ISSUE THREAD

**Issue by davidtolosa** [davidtolosa/matricesDistribuidas#2]
Al conectarse dos veces con un cliente, no simultáneamente, sino conectar,desconectar, conectar, desconcetar, al desconectar la ultima vez se cae el server con el siguiente error: 

`sysmalloc: Assertion (old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
Aborted (core dumped)`

**Comment by renzohcoronel** [comment]
El tema se soluciono debugueando con el  valgrind, habia lugares de memoria corrupta y punteros que no los liberabamos. Ademas de cargar la longitud incorrecta en el buffer que utilizamos para enviar.

**Comment by davidtolosa** [comment]
Solucionado por  @renzohcoronel: El tema se soluciono debugueando con el valgrind, habia lugares de memoria corrupta y punteros que no los liberabamos. Ademas de cargar la longitud incorrecta en el buffer que utilizamos para enviar.
